<a href="https://colab.research.google.com/github/abhi161188/pytorch_learning/blob/main/dataset_and_dataloader_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [4]:
x, y = make_classification(
    n_samples= 10, # Number of samples
    n_features= 2, # Number of features
    n_classes= 2, # Number of classes
    n_informative= 2, # Number of informative features
    n_redundant= 0, # Number of redundant features
    random_state= 42 # Random state

)

In [8]:
x

NameError: name 'X' is not defined

In [6]:
x.shape

(10, 2)

In [7]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [9]:
# convert the data to PyTorch tensors
x = torch.tensor(x, dtype= torch.float32)
y = torch.tensor(y, dtype= torch.long)

In [10]:
x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [11]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [12]:
from torch.utils.data import Dataset, DataLoader

In [13]:
class CustomeDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [14]:
dataset = CustomeDataset(x, y)

In [15]:
len(dataset)

10

In [16]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [18]:
dataloader = DataLoader(dataset, batch_size= 2, shuffle= True)

In [20]:
for batch_feature, batch_label in dataloader:
  print(batch_feature)
  print(batch_label)
  print("--"*50)

tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]])
tensor([0, 0])
----------------------------------------------------------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-1.1402, -0.8388]])
tensor([1, 0])
----------------------------------------------------------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.0683, -0.9701]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
----------------------------------------------------------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.8997,  0.8344]])
tensor([0, 1])
----------------------------------------------------------------------------------------------------
