<a href="https://colab.research.google.com/github/abhi161188/pytorch_learning/blob/main/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available! Using CPU")

GPU is not available! Using CPU


# Creating a Tensor

In [5]:
# using empty
a = torch.empty(2,3)

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using random
torch.rand(2,3)

tensor([[0.7437, 0.7553, 0.0055],
        [0.1429, 0.9920, 0.4385]])

In [10]:
# use of seed
torch.rand(2,3)

tensor([[0.4460, 0.9185, 0.3810],
        [0.2235, 0.2648, 0.5244]])

In [11]:
# manual seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [13]:
# Using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
#other ways

# using arange
print("using arange -> ", torch.arange(0,10,2))

# using linspace
print("using linspace -> ", torch.linspace(0,10,10))

# using eye
print("using eye -> ", torch.eye(5))

# using full
print("using full -> ", torch.full((3, 5), 5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])
